### ISSUE TITLE
internal/origins: add fuzzer for Parse

### ISSUE THREAD

**Issue by dolmen** [jub0bs/cors#3]
Add [fuzzer](https://go.dev/doc/tutorial/fuzz) that compares results of [`Parse`](https://pkg.go.dev/github.com/jub0bs/cors/internal/origins#Parse) with [`net.SplitHostPort`](https://pkg.go.dev/net#SplitHostPort) using [`parseCases`](https://github.com/jub0bs/cors/blob/ecbf8742bcdb12d6d932e2cc535be1b16fb73fb2/internal/origins/origins_test.go#L8) as seed corpus.

**Comment by jub0bs** [comment]
I'll investigate, but I believe `net.SplitHostPort` to be way more lax than my `Parse` function.

**Comment by jub0bs** [comment]
@dolmen I added a fuzz test for checking the consistency of `origins.Parse` with `net.SplitHostPort` and ran it for a while. It hasn't reveal anything that I didn't already know, but I'm happy to have it. Thanks for the suggestion.
